version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
